name: ci

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

#     Build Docker image:
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Verify
        run: mvn clean -B install
      
#     Build Docker image:
      - name: Build and tag image
        run: |
          docker build -f ./devops/Dockerfile -t "${{ secrets.DOCKERHUB_USERNAME }}/conference-demo:latest" -t "${{ secrets.DOCKERHUB_USERNAME }}/conference-demo:${{ github.sha }}" .
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

#     Publish image to DockerHub:
      - name: Publish image
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/conference-demo"

#     Deploy image to Kubernetes
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image --record deployment/mpact-backend-deployment mpact-backend=${{ secrets.DOCKERHUB_USERNAME }}/conference-demo:${{ github.sha }}
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: '"rollout status deployment/mpact-backend-deployment"'